### ISSUE TITLE
Titlebar button not coloured

### ISSUE THREAD

**Issue by ShiinaScripts** [discord-extensions/macos-titlebar#1]
Just suddenly stopped working and only the close button is coloured
[image](https://i.imgur.com/Uww6k0g.png)

Not sure why and I have very little knowledge about css so I am unable to fix it myself

Win10 / win11 with betterdiscord, no other themes applied

**Comment by LuckFire** [comment]
unable to reproduce this issue; please reinstall the theme and see if that fixes it.
if not, feel free to reopen this issue with more details.

tip: make sure you have no custom css / theme that would mess with it.
