### ISSUE TITLE
Move to the right?

### ISSUE THREAD

**Issue by Stebulous** [discord-extensions/macos-titlebar#3]
I know the whole point is to match MacOS but i would really like to just have the round icons on the right, is there something i can change in the css to make this happen?

**Comment by LuckFire** [comment]
You ARE able to move it to the right by changing some values around but it won't be easy due to it practically being made for having one purpose.

**Comment by dhruvnnd** [comment]
@LuckFire what exactly are those values?

**Comment by LuckFire** [comment]
> @LuckFire what exactly are those values? 

What values

**Comment by dhruvnnd** [comment]
> You ARE able to move it to the right by changing some values

The one you are talking about in [here](https://github.com/Discord-Theme-Addons/macos-titlebar/issues/3#issuecomment-972989535)

**Comment by LuckFire** [comment]
positioning values in the [source](https://github.com/Discord-Theme-Addons/macos-titlebar/blob/master/src/_theme.scss). you'd have to tinker around with stuff to get what you'd like
