### ISSUE TITLE
Macos-titlebar not showing.

### ISSUE THREAD

**Issue by IamNickerson** [discord-extensions/macos-titlebar#6]
Hey,
The Macos-titleBar is not showing up in discord it could be an update which it caused it.
![image](https://user-images.githubusercontent.com/61643704/169676532-5b496c62-cd10-4169-938f-651b7878dcbe.png)

**Comment by LuckFire** [comment]
You will have to redownload the theme. Just head over to this link and save the file to your themes folder.
https://github.com/discord-extensions/macos-titlebar/releases/download/betterdiscord/macos-titlebar.theme.css

**Comment by IamNickerson** [comment]
Alright

**Comment by IamNickerson** [comment]
Ok works again by doing that.
