### ISSUE TITLE
As of today (28.03.24) the theme stopped working

### ISSUE THREAD

**Issue by Skyyblaze** [discord-extensions/macos-titlebar#9]
The macOS titlebar theme worked fine last night before it reverted back to the standard Discord titlebar today so I suspect Discord has changed things again, can this be looked into?

One thing I noticed, there's a weird circle next to the "Discord" text:

![grafik](https://github.com/discord-extensions/macos-titlebar/assets/22203339/c123ddb9-25d3-442f-9fac-13f80b7a4abe)

So I guess the theme tries to do something still.

**Comment by LuckFire** [comment]
Discord recently pushed a build that messes up themes; I'll look into fixing this soon.

**Comment by Skyyblaze** [comment]
I see, thank you very much! Your theme is one that really makes Discord more pleasing to use, I appreciate your work.

**Comment by LuckFire** [comment]
Sorry that it took so long to get this fix out, thank you for your patience!

**Comment by Skyyblaze** [comment]
No worries, thanks for the hard work, it works like a charm again! I noticed I still have that weird black circle but realized it wasn't related to any theme so it must be an issue with Better Discord itself.

**Comment by LuckFire** [comment]
Can you elaborate on the "weird black circle" thing?

**Comment by Skyyblaze** [comment]
Look at my screenshot in the initial post, it's right to the "Discord" logo-text even without any themes.
